public class PharmaIDFetch {
/*
   @AuraEnabled
    public static pharma_product__c saveRecord(pharma_product__c objDetail)
    {
        system.debug('entered from controller');

        if(objDetail !=  null){
            pharma_product__c wr = objDetail;
          // system.debug('f name'+wr.First_Name__c);
          //  wr.Status__c = 'Assigned';
            insert wr;
            system.debug('success');
            system.debug('id:'+wr.Id);
        }        
       return objDetail;  
        }  */
}